inherit_from: .rubocop.standards.yml

AllCops:
  TargetRubyVersion: ~
  Exclude:
    - 'db/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Exclude:
    - '*.gemspec'
