language: ruby
rvm:
  - 2.4.2
before_install:
  - cp config/database.yml.example config/database.yml
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.5"
